### PR TITLE
Element value should be preserved on load

### PR DESCRIPTION
**Pull request by mostly-magic**
Hey,

Just a small fix. If the input element has a value when the page is loaded, that value should stay, instead of overwriting with the placeholder text.

Cheers,
Mitchell

### CODE REVIEW

**Comment by gabeins** [comment]
Good point! I also think that password fields should be treated differently. Maybe not applying the placeholder at all. If the form gets submitted, the placeholder will be the password value and the developer will be forced to test it.

**Comment by danbentley** [comment]
Yeah, cheers for this!

About the password fields, csswizardry and I discussed adding a clause to exclude password fields but decided against it. 

The reasons escape me...

It's simple enough to add, if needed.

**Comment by mostly-magic** [comment]
Glad I could help.

**Comment by csswizardry** [comment]
The reason was: if you're using IE et al you must be used to a sub-par experience everywhere on the web.

As this plugin is nice and progressive, we thought it more pragmatic to deliver a bog-standard experience on password fields rather than bloating/altering the code to _fully_ cater for an edge case.

I think that's right…

H

**Comment by gabeins** [comment]
Yeah it makes sense.. and it doesn't require too much effort to test the value of the password field before submitting it anyway.

**Pull request merged**
